services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U petclinic -d petclinic'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgresV:/var/lib/postgresql/data
    ports:
      - "2012:5432"
    restart: on-failure # Restart the db service on failure
  
  app:
    build:
      context: .
      target: prod
    ports:
      - ":8080"
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_URL=jdbc:postgresql://db:5432/petclinic
      - SPRING_PROFILES_ACTIVE=postgres
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
    restart: on-failure # Restart the app service on failure

volumes:
  postgresV:
  # psql -U petclinic -h 127.0.0.1 -p 2012
