services:
  app:
    build:
      context: .
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s

  load_balancer:
    image: nginx:latest
    volumes:
      - /home/mostafa/hello/conf.d:/etc/nginx/conf.d/
    ports:
      - :80
    depends_on:
      - app

