services:
  db:
    image: mysql:latest
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="root" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    ports:
      - "4004:3306"
    volumes:
      - volumedb:/var/lib/mysql
  app:
    build: .
    ports:
      - "4005:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
     
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_PROFILES_ACTIVE=mysql
volumes:
  volumedb:
  # mysql -u petclinic -p -h 127.0.0.1 -P 4004
  # USE petclinic
  